--------------------------------------------------------
--  파일이 생성됨 - 화요일-8월-08-2023   
--------------------------------------------------------
DROP TABLE "CANONKOREA"."CANON_NOTICE_TBL" cascade constraints;
DROP TABLE "CANONKOREA"."CANON_MEMBER_TBL" cascade constraints;
--------------------------------------------------------
--  DDL for Table CANON_NOTICE_TBL
--------------------------------------------------------

  CREATE TABLE "CANONKOREA"."CANON_NOTICE_TBL" 
   (	"NOTICE_NO" NUMBER, 
	"NOTICE_TITLE" VARCHAR2(50 BYTE), 
	"NOTICE_CONTENTS" VARCHAR2(50 BYTE), 
	"NOTICE_REGDATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CANON_MEMBER_TBL
--------------------------------------------------------

  CREATE TABLE "CANONKOREA"."CANON_MEMBER_TBL" 
   (	"MEMBER_ID" VARCHAR2(100 BYTE), 
	"MEMBER_PW" VARCHAR2(100 BYTE), 
	"MEMBER_NAME" VARCHAR2(50 BYTE), 
	"MEMBER_AGE" NUMBER, 
	"MEMBER_GENDER" VARCHAR2(10 BYTE), 
	"MEMBER_EMAIL" VARCHAR2(100 BYTE), 
	"MEMBER_PHONE" VARCHAR2(100 BYTE), 
	"MEMBER_ADDRESS" VARCHAR2(100 BYTE), 
	"MEMBER_HOBBY" VARCHAR2(50 BYTE), 
	"MEMBER_DATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATE_DATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"MEMBER_YN" VARCHAR2(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into CANONKOREA.CANON_NOTICE_TBL
SET DEFINE OFF;
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (931,'공지사항279번째','공지사항내용279번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (932,'공지사항280번째','공지사항내용280번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (933,'공지사항281번째','공지사항내용281번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (934,'공지사항282번째','공지사항내용282번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (935,'공지사항283번째','공지사항내용283번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (936,'공지사항284번째','공지사항내용284번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (937,'공지사항285번째','공지사항내용285번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (938,'공지사항286번째','공지사항내용286번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (939,'공지사항287번째','공지사항내용287번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (940,'공지사항288번째','공지사항내용288번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (941,'공지사항289번째','공지사항내용289번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (942,'공지사항290번째','공지사항내용290번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (943,'공지사항291번째','공지사항내용291번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (944,'공지사항292번째','공지사항내용292번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (945,'공지사항293번째','공지사항내용293번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (946,'공지사항294번째','공지사항내용294번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (947,'공지사항295번째','공지사항내용295번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (948,'공지사항296번째','공지사항내용296번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (949,'공지사항297번째','공지사항내용297번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (950,'공지사항298번째','공지사항내용298번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (951,'공지사항299번째','공지사항내용299번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (952,'공지사항300번째','공지사항내용300번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (953,'공지사항301번째','공지사항내용301번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (954,'공지사항302번째','공지사항내용302번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (955,'공지사항303번째','공지사항내용303번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (956,'공지사항입니다~~','공지사항입니다~~~~~~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (957,'수정좀되라','수정좀되라ㅇ ㅇㅇㅇ',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (958,'수정좀되라','수정좀되라ㅇ ㅇㅇㅇ',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (959,'공지사항입력!!','공지사항입력!!~~~~~0804',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (839,'공지사항187번째','공지사항내용187번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (840,'공지사항188번째','공지사항내용188번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (841,'공지사항189번째','공지사항내용189번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (842,'공지사항190번째','공지사항내용190번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (843,'공지사항191번째','공지사항내용191번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (844,'공지사항192번째','공지사항내용192번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (845,'공지사항193번째','공지사항내용193번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (846,'공지사항194번째','공지사항내용194번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (847,'공지사항195번째','공지사항내용195번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (848,'공지사항196번째','공지사항내용196번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (849,'공지사항197번째','공지사항내용197번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (850,'공지사항198번째','공지사항내용198번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (851,'공지사항199번째','공지사항내용199번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (852,'공지사항200번째','공지사항내용200번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (854,'공지사항202번째','공지사항내용202번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (855,'공지사항203번째','공지사항내용203번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (856,'공지사항204번째','공지사항내용204번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (857,'공지사항205번째','공지사항내용205번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (858,'공지사항206번째','공지사항내용206번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (859,'공지사항207번째','공지사항내용207번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (860,'공지사항208번째','공지사항내용208번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (861,'공지사항209번째','공지사항내용209번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (862,'공지사항210번째','공지사항내용210번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (863,'공지사항211번째','공지사항내용211번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (864,'공지사항212번째','공지사항내용212번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (865,'공지사항213번째','공지사항내용213번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (866,'공지사항214번째','공지사항내용214번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (867,'공지사항215번째','공지사항내용215번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (868,'공지사항216번째','공지사항내용216번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (869,'공지사항217번째','공지사항내용217번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (870,'공지사항218번째','공지사항내용218번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (871,'공지사항219번째','공지사항내용219번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (872,'공지사항220번째','공지사항내용220번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (873,'공지사항221번째','공지사항내용221번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (874,'공지사항222번째','공지사항내용222번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (875,'공지사항223번째','공지사항내용223번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (876,'공지사항224번째','공지사항내용224번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (877,'공지사항225번째','공지사항내용225번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (878,'공지사항226번째','공지사항내용226번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (879,'공지사항227번째','공지사항내용227번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (880,'공지사항228번째','공지사항내용228번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (881,'공지사항229번째','공지사항내용229번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (882,'공지사항230번째','공지사항내용230번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (883,'공지사항231번째','공지사항내용231번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (884,'공지사항232번째','공지사항내용232번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (885,'공지사항233번째','공지사항내용233번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (886,'공지사항234번째','공지사항내용234번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (887,'공지사항235번째','공지사항내용235번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (888,'공지사항236번째','공지사항내용236번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (889,'공지사항237번째','공지사항내용237번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (890,'공지사항238번째','공지사항내용238번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (891,'공지사항239번째','공지사항내용239번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (892,'공지사항240번째','공지사항내용240번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (893,'공지사항241번째','공지사항내용241번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (894,'공지사항242번째','공지사항내용242번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (895,'공지사항243번째','공지사항내용243번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (896,'공지사항244번째','공지사항내용244번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (897,'공지사항245번째','공지사항내용245번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (898,'공지사항246번째','공지사항내용246번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (899,'공지사항247번째','공지사항내용247번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (900,'공지사항900번째수정','공지사항900번째수정111111',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (901,'공지사항249번째','공지사항내용249번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (902,'공지사항250번째','공지사항내용250번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (903,'공지사항251번째','공지사항내용251번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (904,'공지사항252번째','공지사항내용252번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (905,'공지사항253번째','공지사항내용253번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (906,'공지사항254번째','공지사항내용254번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (907,'공지사항255번째','공지사항내용255번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (908,'공지사항256번째','공지사항내용256번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (909,'공지사항257번째','공지사항내용257번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (910,'공지사항258번째','공지사항내용258번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (911,'공지사항259번째','공지사항내용259번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (912,'공지사항260번째','공지사항내용260번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (913,'공지사항261번째','공지사항내용261번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (914,'공지사항262번째','공지사항내용262번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (915,'공지사항263번째','공지사항내용263번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (916,'공지사항264번째','공지사항내용264번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (917,'공지사항265번째','공지사항내용265번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (918,'공지사항266번째','공지사항내용266번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (919,'공지사항267번째','공지사항내용267번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (920,'공지사항268번째','공지사항내용268번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (921,'공지사항269번째','공지사항내용269번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (922,'공지사항270번째','공지사항내용270번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (923,'공지사항271번째','공지사항내용271번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (924,'공지사항272번째','공지사항내용272번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (925,'공지사항273번째','공지사항내용273번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (926,'공지사항274번째','공지사항내용274번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (927,'공지사항275번째','공지사항내용275번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (928,'공지사항276번째','공지사항내용276번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (929,'공지사항277번째','공지사항내용277번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (930,'공지사항278번째','공지사항내용278번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (747,'공지사항95번째','공지사항내용95번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (748,'공지사항96번째','공지사항내용96번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (749,'공지사항97번째','공지사항내용97번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (750,'공지사항98번째','공지사항내용98번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (751,'공지사항99번째','공지사항내용99번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (752,'공지사항100번째','공지사항내용100번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (753,'공지사항101번째','공지사항내용101번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (754,'공지사항102번째','공지사항내용102번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (755,'공지사항103번째','공지사항내용103번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (756,'공지사항104번째','공지사항내용104번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (757,'공지사항105번째','공지사항내용105번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (758,'공지사항106번째','공지사항내용106번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (759,'공지사항107번째','공지사항내용107번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (760,'공지사항108번째','공지사항내용108번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (761,'공지사항109번째','공지사항내용109번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (762,'공지사항110번째','공지사항내용110번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (763,'공지사항111번째','공지사항내용111번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (764,'공지사항112번째','공지사항내용112번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (765,'공지사항113번째','공지사항내용113번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (766,'공지사항114번째','공지사항내용114번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (767,'공지사항115번째','공지사항내용115번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (768,'공지사항116번째','공지사항내용116번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (769,'공지사항117번째','공지사항내용117번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (770,'공지사항118번째','공지사항내용118번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (771,'공지사항119번째','공지사항내용119번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (772,'공지사항120번째','공지사항내용120번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (773,'공지사항121번째','공지사항내용121번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (774,'공지사항122번째','공지사항내용122번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (775,'공지사항123번째','공지사항내용123번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (776,'공지사항124번째','공지사항내용124번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (777,'공지사항125번째','공지사항내용125번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (778,'공지사항126번째','공지사항내용126번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (779,'공지사항127번째','공지사항내용127번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (780,'공지사항128번째','공지사항내용128번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (781,'공지사항129번째','공지사항내용129번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (782,'공지사항130번째','공지사항내용130번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (783,'공지사항131번째','공지사항내용131번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (784,'공지사항132번째','공지사항내용132번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (785,'공지사항133번째','공지사항내용133번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (786,'공지사항134번째','공지사항내용134번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (787,'공지사항135번째','공지사항내용135번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (788,'공지사항136번째','공지사항내용136번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (789,'공지사항137번째','공지사항내용137번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (790,'공지사항138번째','공지사항내용138번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (791,'공지사항139번째','공지사항내용139번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (792,'공지사항140번째','공지사항내용140번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (793,'공지사항141번째','공지사항내용141번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (794,'공지사항142번째','공지사항내용142번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (795,'공지사항143번째','공지사항내용143번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (796,'공지사항144번째','공지사항내용144번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (797,'공지사항145번째','공지사항내용145번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (798,'공지사항146번째','공지사항내용146번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (799,'공지사항147번째','공지사항내용147번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (800,'공지사항148번째','공지사항내용148번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (801,'공지사항149번째','공지사항내용149번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (802,'공지사항150번째','공지사항내용150번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (803,'공지사항151번째','공지사항내용151번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (804,'공지사항152번째','공지사항내용152번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (805,'공지사항153번째','공지사항내용153번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (806,'공지사항154번째','공지사항내용154번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (807,'공지사항155번째','공지사항내용155번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (808,'공지사항156번째','공지사항내용156번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (809,'공지사항157번째','공지사항내용157번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (810,'공지사항158번째','공지사항내용158번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (811,'공지사항159번째','공지사항내용159번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (812,'공지사항160번째','공지사항내용160번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (813,'공지사항161번째','공지사항내용161번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (814,'공지사항162번째','공지사항내용162번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (815,'공지사항163번째','공지사항내용163번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (816,'공지사항164번째','공지사항내용164번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (817,'공지사항165번째','공지사항내용165번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (818,'공지사항166번째','공지사항내용166번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (819,'공지사항167번째','공지사항내용167번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (820,'공지사항168번째','공지사항내용168번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (821,'공지사항169번째','공지사항내용169번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (822,'공지사항170번째','공지사항내용170번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (823,'공지사항171번째','공지사항내용171번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (824,'공지사항172번째','공지사항내용172번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (825,'공지사항173번째','공지사항내용173번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (826,'공지사항174번째','공지사항내용174번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (827,'공지사항175번째','공지사항내용175번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (828,'공지사항176번째','공지사항내용176번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (829,'공지사항177번째','공지사항내용177번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (830,'공지사항178번째','공지사항내용178번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (831,'공지사항179번째','공지사항내용179번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (832,'공지사항180번째','공지사항내용180번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (833,'공지사항181번째','공지사항내용181번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (834,'공지사항182번째','공지사항내용182번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (835,'공지사항183번째','공지사항내용183번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (836,'공지사항184번째','공지사항내용184번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (837,'공지사항185번째','공지사항내용185번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (838,'공지사항186번째','공지사항내용186번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (682,'공지사항30번째','공지사항내용30번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (683,'공지사항31번째','공지사항내용31번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (684,'공지사항32번째','공지사항내용32번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (685,'공지사항33번째','공지사항내용33번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (686,'공지사항34번째','공지사항내용34번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (687,'공지사항35번째','공지사항내용35번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (688,'공지사항36번째','공지사항내용36번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (689,'공지사항37번째','공지사항내용37번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (690,'공지사항38번째','공지사항내용38번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (691,'공지사항39번째','공지사항내용39번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (692,'공지사항40번째','공지사항내용40번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (693,'공지사항41번째','공지사항내용41번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (694,'공지사항42번째','공지사항내용42번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (695,'공지사항43번째','공지사항내용43번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (696,'공지사항44번째','공지사항내용44번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (697,'공지사항45번째','공지사항내용45번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (698,'공지사항46번째','공지사항내용46번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (699,'공지사항47번째','공지사항내용47번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (700,'공지사항48번째','공지사항내용48번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (701,'공지사항49번째','공지사항내용49번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (702,'공지사항50번째','공지사항내용50번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (703,'공지사항51번째','공지사항내용51번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (704,'공지사항52번째','공지사항내용52번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (705,'공지사항53번째','공지사항내용53번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (706,'공지사항54번째','공지사항내용54번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (707,'공지사항55번째','공지사항내용55번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (708,'공지사항56번째','공지사항내용56번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (709,'공지사항57번째','공지사항내용57번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (710,'공지사항58번째','공지사항내용58번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (711,'공지사항59번째','공지사항내용59번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (712,'공지사항60번째','공지사항내용60번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (713,'공지사항61번째','공지사항내용61번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (714,'공지사항62번째','공지사항내용62번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (715,'공지사항63번째','공지사항내용63번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (716,'공지사항64번째','공지사항내용64번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (717,'공지사항65번째','공지사항내용65번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (718,'공지사항66번째','공지사항내용66번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (719,'공지사항67번째','공지사항내용67번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (720,'공지사항68번째','공지사항내용68번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (721,'공지사항69번째','공지사항내용69번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (722,'공지사항70번째','공지사항내용70번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (723,'공지사항71번째','공지사항내용71번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (724,'공지사항72번째','공지사항내용72번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (725,'공지사항73번째','공지사항내용73번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (726,'공지사항74번째','공지사항내용74번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (727,'공지사항75번째','공지사항내용75번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (728,'공지사항76번째','공지사항내용76번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (729,'공지사항77번째','공지사항내용77번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (730,'공지사항78번째','공지사항내용78번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (731,'공지사항79번째','공지사항내용79번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (732,'공지사항80번째','공지사항내용80번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (733,'공지사항81번째','공지사항내용81번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (734,'공지사항82번째','공지사항내용82번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (735,'공지사항83번째','공지사항내용83번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (736,'공지사항84번째','공지사항내용84번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (737,'공지사항85번째','공지사항내용85번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (738,'공지사항86번째','공지사항내용86번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (739,'공지사항87번째','공지사항내용87번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (740,'공지사항88번째','공지사항내용88번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (741,'공지사항89번째','공지사항내용89번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (742,'공지사항90번째','공지사항내용90번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (743,'공지사항91번째','공지사항내용91번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (744,'공지사항92번째','공지사항내용92번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (745,'공지사항93번째','공지사항내용93번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (653,'공지사항1번째','공지사항내용1번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (654,'공지사항2번째','공지사항내용2번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (655,'공지사항3번째','공지사항내용3번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (656,'공지사항4번째','공지사항내용4번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (657,'공지사항5번째','공지사항내용5번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (658,'공지사항6번째','공지사항내용6번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (659,'공지사항7번째','공지사항내용7번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (660,'공지사항8번째','공지사항내용8번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (661,'공지사항9번째','공지사항내용9번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (662,'공지사항10번째','공지사항내용10번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (663,'공지사항11번째','공지사항내용11번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (664,'공지사항12번째','공지사항내용12번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (665,'공지사항13번째','공지사항내용13번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (666,'공지사항14번째','공지사항내용14번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (667,'공지사항15번째','공지사항내용15번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (668,'공지사항16번째','공지사항내용16번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (669,'공지사항17번째','공지사항내용17번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (670,'공지사항18번째','공지사항내용18번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (671,'공지사항19번째','공지사항내용19번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (672,'공지사항20번째','공지사항내용20번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (673,'공지사항21번째','공지사항내용21번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (674,'공지사항22번째','공지사항내용22번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (675,'공지사항23번째','공지사항내용23번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (677,'공지사항25번째','공지사항내용25번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (678,'공지사항26번째','공지사항내용26번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (679,'공지사항27번째','공지사항내용27번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (680,'공지사항28번째','공지사항내용28번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (681,'공지사항29번째','공지사항내용29번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
Insert into CANONKOREA.CANON_NOTICE_TBL (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENTS,NOTICE_REGDATE) values (746,'공지사항94번째','공지사항내용94번째 입니다.~',to_date('23/08/04','RR/MM/DD'));
REM INSERTING into CANONKOREA.CANON_MEMBER_TBL
SET DEFINE OFF;
Insert into CANONKOREA.CANON_MEMBER_TBL (MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_AGE,MEMBER_GENDER,MEMBER_EMAIL,MEMBER_PHONE,MEMBER_ADDRESS,MEMBER_HOBBY,MEMBER_DATE,UPDATE_DATE,MEMBER_YN) values ('khuser01','pass01','일용자',11,'F','khuser01@kh.com','01011111111','경기도 안양시','물놀이',to_timestamp('23/08/07 10:02:39.194000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('23/08/07 10:02:39.194000000','RR/MM/DD HH24:MI:SSXFF'),'Y');
Insert into CANONKOREA.CANON_MEMBER_TBL (MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_AGE,MEMBER_GENDER,MEMBER_EMAIL,MEMBER_PHONE,MEMBER_ADDRESS,MEMBER_HOBBY,MEMBER_DATE,UPDATE_DATE,MEMBER_YN) values ('khuser02','pass02','이용자',22,'M','khuser02@kh.com','0102222222','서울시 권선구','투호놀이',to_timestamp('23/08/07 10:03:32.646000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('23/08/07 10:03:32.646000000','RR/MM/DD HH24:MI:SSXFF'),'Y');
Insert into CANONKOREA.CANON_MEMBER_TBL (MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_AGE,MEMBER_GENDER,MEMBER_EMAIL,MEMBER_PHONE,MEMBER_ADDRESS,MEMBER_HOBBY,MEMBER_DATE,UPDATE_DATE,MEMBER_YN) values ('khuser03','pass03','삼용자',33,'M','khuser03@kh.com','01033333333','서울시 팔달구','축구하기',to_timestamp('23/08/07 10:04:08.642000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('23/08/07 10:04:08.642000000','RR/MM/DD HH24:MI:SSXFF'),'Y');
--------------------------------------------------------
--  DDL for Index SYS_C007051
--------------------------------------------------------

  CREATE UNIQUE INDEX "CANONKOREA"."SYS_C007051" ON "CANONKOREA"."CANON_NOTICE_TBL" ("NOTICE_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007058
--------------------------------------------------------

  CREATE UNIQUE INDEX "CANONKOREA"."SYS_C007058" ON "CANONKOREA"."CANON_MEMBER_TBL" ("MEMBER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CANON_NOTICE_TBL
--------------------------------------------------------

  ALTER TABLE "CANONKOREA"."CANON_NOTICE_TBL" ADD PRIMARY KEY ("NOTICE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CANONKOREA"."CANON_NOTICE_TBL" MODIFY ("NOTICE_CONTENTS" NOT NULL ENABLE);
  ALTER TABLE "CANONKOREA"."CANON_NOTICE_TBL" MODIFY ("NOTICE_TITLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CANON_MEMBER_TBL
--------------------------------------------------------

  ALTER TABLE "CANONKOREA"."CANON_MEMBER_TBL" ADD PRIMARY KEY ("MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CANONKOREA"."CANON_MEMBER_TBL" MODIFY ("MEMBER_NAME" NOT NULL ENABLE);
  ALTER TABLE "CANONKOREA"."CANON_MEMBER_TBL" MODIFY ("MEMBER_PW" NOT NULL ENABLE);

commit